### ISSUE TITLE
Calculate the shapley value

### ISSUE THREAD

**Issue by ghost** [Hyungsik-Jung/LIFT-CAM#1]
Thank you for your excellent work! But I have a question, I don't see the calculation of the Shapley value in your LIFT-CAM method. However, I see DeepLiftShap in the init.py of captum.attr, but it runs very slowly.

**Comment by Hyungsik-Jung** [comment]
Sorry for the late response. 
1. LIFT-CAM doesn't require to calculate the SHAP values of the activation maps. Instead, it utilizes DeepLIFT method to approximate the SHAP values with the single reference value, 0.
2. I am not sure about the exact code for DeepLiftShap in captum.attr, but it might requires the multiple reference values. In other words, it calculates multiple DeepLIFT values from multiple reference values and averages them. That's the reason for the high latency.

**Comment by ghost** [comment]
@Hyungsik-Jung thank you for your reply！you helped me solve this problem.
